# EJERCICIO 1

SELECT ASIGNATURA 
  FROM IMPARTIR
 WHERE PROFESOR = (SELECT ID 
					FROM PROFESORES
                   WHERE UPPER(NOMBRE) = "Manuel"
                     AND UPPER(APELLIDO1) = "Enciso");


# EJERCICIO 2

SELECT ALUMNO 
  FROM MATRICULAR 
 WHERE (ASIGNATURA, CURSO, GRUPO) IN (SELECT ASIGNATURA, CURSO, GRUPO FROM IMPARTIR WHERE PROFESOR = 'C-34-TU-00');
 
 
# EJERCICIO 3 

SELECT D.NOMBRE, SUM(CREDITOS)
  FROM ASIGNATURAS ASI JOIN DEPARTAMENTOS D ON (ASI.DEPARTAMENTO = D.CODIGO)
 GROUP BY DEPARTAMENTO;
 
 
# EJERCICIO 4

SELECT p.despacho, SUM(i.carga_creditos) AS 'CARGA_CREDITOS'
  FROM profesores p JOIN impartir i ON i.profesor=p.ID
  WHERE CARGA_CREDITOS IS NOT NULL
 GROUP BY p.despacho;


# EJERCICIO 5 
    
SELECT DISTINCT(CONCAT(A.NOMBRE, ' ', A.APELLIDO1)) "ALUMNO" , ASIG.NOMBRE "ASIGNATURA"
FROM ALUMNOS A , ASIGNATURAS ASIG, MATRICULAR M
WHERE M.ALUMNO=A.DNI and M.ASIGNATURA=ASIG.CODIGO
     and ASIG.CREDITOS=(SELECT MAX(ASIG1.CREDITOS) FROM ASIGNATURAS ASIG1, MATRICULAR M1
        WHERE M1.ASIGNATURA=ASIG1.CODIGO AND M1.ALUMNO=A.DNI);    
                    
  
  
# EJERCICIO 6
 
SELECT D.NOMBRE, ASI.NOMBRE, CREDITOS 
  FROM ASIGNATURAS ASI JOIN DEPARTAMENTOS D ON (ASI.DEPARTAMENTO = D.CODIGO)
 WHERE (DEPARTAMENTO, CREDITOS) IN (SELECT DEPARTAMENTO, MIN(CREDITOS) AS CREDITOS FROM ASIGNATURAS GROUP BY DEPARTAMENTO)
 ORDER BY DEPARTAMENTO;
 
 
 
# EJERCICIO 7 

SELECT DEPARTAMENTO, D.NOMBRE, SUM(CREDITOS)
  FROM ASIGNATURAS ASI JOIN DEPARTAMENTOS D ON (ASI.DEPARTAMENTO =  D.CODIGO)
 GROUP BY DEPARTAMENTO
  HAVING SUM(CREDITOS) = (SELECT MAX(TEMP.SUMA) FROM (SELECT SUM(CREDITOS)  'SUMA' 
													    FROM ASIGNATURAS GROUP BY DEPARTAMENTO) AS TEMP);
  
 
  
  
# EJERCICIO 8

SELECT CONCAT(P.NOMBRE, ' ', P.APELLIDO1, ' ', P.APELLIDO2) AS "PROFESOR", SUM(ASI.CREDITOS)
  FROM PROFESORES P JOIN IMPARTIR I ON (P.ID=I.PROFESOR) JOIN ASIGNATURAS ASI ON (I.ASIGNATURA = ASI.CODIGO)
 GROUP BY CONCAT(P.NOMBRE, ' ', P.APELLIDO1, ' ', P.APELLIDO2) 
  HAVING SUM(I.CARGA_CREDITOS) > (SELECT AVG(TEMP.SUMA) 
                                FROM (SELECT SUM(CARGA_CREDITOS)  'SUMA' 
                                        FROM IMPARTIR I JOIN ASIGNATURAS ASI ON (I.ASIGNATURA = ASI.CODIGO) GROUP BY I.PROFESOR) AS TEMP);
                                        
									

# EJERCICIO 9

SELECT D.NOMBRE
  FROM DEPARTAMENTOS D 
 WHERE D.NOMBRE NOT IN (SELECT D1.NOMBRE 
                          FROM DEPARTAMENTOS D1, ASIGNATURAS ASI
					     WHERE D1.CODIGO=ASI.DEPARTAMENTO AND ASI.CREDITOS > 6);



# EJERCICIO 10

SELECT CONCAT(P1.NOMBRE, ' ', P1.APELLIDO1, ' ', IFNULL(P1.APELLIDO2, ' ')) AS 'PROFESOR1', 
       CONCAT(P2.NOMBRE, ' ', P2.APELLIDO1, ' ', IFNULL(P2.APELLIDO2, ' ')) AS 'PROFESOR2'                                      
FROM PROFESORES P1 JOIN PROFESORES P2 ON (P1.ID < P2.ID)
WHERE (P1.ID, P2.ID) != ALL (SELECT DISTINCT I1.PROFESOR, I2.PROFESOR
                               FROM IMPARTIR I1, IMPARTIR I2, MATRICULAR M1, MATRICULAR M2
							  WHERE I1.PROFESOR   != I2.PROFESOR
                                AND I1.ASIGNATURA  = M1.ASIGNATURA
                                AND I2.ASIGNATURA  = M2.ASIGNATURA
                                AND I1.GRUPO       = M1.GRUPO
                                AND I2.GRUPO       = M2.GRUPO
                                AND I1.CURSO       = M1.CURSO
                                AND I2.CURSO       = M2.CURSO
                                AND M1.ALUMNO      = M2.ALUMNO);                                