#QUERIES FOR TOUROPERATOR RELATIONAL DATA BASE || GROUP: RUBEN NAVARRO TRUJILLO, INMACULADA VALERO FRIAS, FERNANDO MUÑOZ RAMIREZ || MODULO 02 DATABASES

#1- NUMBER OF CRUISES THAT STOP IN BARCELONA IN ALL THEIR ROUTES

SELECT ID_CRUISE, COUNT(*) FROM
CRUISE C JOIN PORTS_OF_CALL ON ID_PORT_CRUISE = C.ID_CRUISE
WHERE UPPER(PORT_CALL) = 'BARCELONA'
GROUP BY ID_CRUISE;

#SOLUTION
#CR2001	4
#CR2004	4

#2- FLIGHTS FROM AGP AIRPORT THAT HAVE A PRICE VIP < 13000 AND A PRICE_ECO < 8000

SELECT ID_FLIGHT, PLANE, IATA_ARR, COUNT(*) AS NUMBER
FROM FLIGHT
WHERE IATA_DEP = 'AGP' AND PRICE_VIP < 13000 AND PRICE_ECO < 8000
GROUP BY IATA_ARR;

#SOLUTION
#AZ1010	BOEING 737 	BRU	10
#AZ1018	BOEING M50 	OST	5

#3- FREQUENT LOCATION OF THE BOOKINGS

SELECT L.CONTINENT AS CONTINENT_BOOKING, COUNT(*) AS FREQUENT
	FROM TRAVEL T JOIN SEASON S ON T.SEASON = S.ID_SEASON JOIN LOCATIONS L ON S.ID_SEASON = L.ID_SEASON
    GROUP BY CONTINENT;

#SOLUTION
#EUROPE       	8
#NORTH-AMERICA	3
#SOUTH-AMERICA	5
#ASSSIA         	14

#4- Number of product booked (using the type product flag: 1:FLIGHTS, 2: TRAIN, 3: HOTEL_ROOM, 4: CRUISE)

SELECT PRODUCT_TYPE, SUM(AMOUNT) AS Number_of_product_booked
FROM TRAVEL JOIN PRODUCTS ON ID_PRODUCTS = ID_PROD
GROUP BY PRODUCT_TYPE;

#SOLUTION
#1	29
#2	7
#4	2

#5- Customer that are relative of an employee

SELECT CONCAT('Customer: ', C1.CUST_NAME,' ', C1.SURNAME, ' IS RELATIVE OF EMPLOYEE ', C2.CUST_NAME,' ', C2.SURNAME) AS RELATIVE 
FROM (CUSTOMER C1 JOIN EMPLOYEE_RELATIVE R ON R.ID_CUSTOMER = C1.IDENTIFIER) 
JOIN (CUSTOMER C2 JOIN EMPLOYEE E ON E.ID_CUSTOMER = C2.IDENTIFIER) ON ID_EMPLO = ID_EMPLOYEE;

#Solution
#Customer: Austin     Craig     IS RELATIVE OF EMPLOYEE Geraldine  Castillo 
#Customer: Clarke     Jacobson  IS RELATIVE OF EMPLOYEE Burton     Mccall   
#Customer: Zephr      Deleon    IS RELATIVE OF EMPLOYEE Price      Snyder   
#Customer: Donovan    Solomon   IS RELATIVE OF EMPLOYEE Jayme      Morse    
#Customer: Davis      Fowler    IS RELATIVE OF EMPLOYEE Sylvester  Horne    
#Customer: Adam       Wilson    IS RELATIVE OF EMPLOYEE Garth      Skinner  
#Customer: Drew       Lee       IS RELATIVE OF EMPLOYEE Lucas      Sherman  
#Customer: Cameron    Cervantes IS RELATIVE OF EMPLOYEE Evangeline Nielsen  

#6- TOTAL NUMBER OF ROOM BOOKED (not using type os product flag)

SELECT SUM(AMOUNT) AS NUMBER_OF_SEATS_BOOKED 
FROM TRAVEL T JOIN 
((PRODUCTS P LEFT OUTER JOIN SEATS S ON S.ID_PROD = P.ID_PRODUCTS) LEFT OUTER JOIN ROOMS R ON R.ID_PRODU = P.ID_PRODUCTS) ON T.ID_PROD = P.ID_PRODUCTS 
WHERE ID_ALLOT IS NULL;

#Solution
#36

#7- NUMBER OF TRAIN GROUPING BY CITY WITH DESTINATION SEVILLA


SELECT ID_TRAIN AS TRAIN, DEP_TRAIN_CITY AS DEPARTURE, COUNT(*) AS NUMBER_OF_TRAIN
	FROM TRAIN
    WHERE UPPER(ARR_TRAIN_CITY) = 'SEVILLA'
    GROUP BY DEP_TRAIN_CITY;

#Solution
#'TAL014', 'MADRID     ', '4'
#'TAL016', 'CORDOBA    ', '4'


#8- TOTAL EXPEND IN BOOKINGS OF CUSTOMER WHO BOOKS VIP SEATS IN FLIGHT

SELECT CONCAT(C.CUST_NAME,' ', C.SURNAME) AS CUSTOMER, AMOUNT*PRICE_ECO AS TOTAL_EXPEND
	FROM CUSTOMER C JOIN (BOOKS B JOIN 
    (TRAVEL T JOIN (SEATS S JOIN FLIGHT F ON S.ID_PROD = F.ID_PRODUCT) ON S.ID_PROD = T.ID_PROD) ON B.BOOK_NUMBER = T.BOOK_NUMBER) ON B.ID_CUST = C.IDENTIFIER 
    WHERE TYPE_SEAT = 'V' 
    GROUP BY CUSTOMER
    ORDER BY TOTAL_EXPEND DESC;

#Solution
#'Evangeline Nielsen  ', '47000.00'
#'Travis     Vazquez  ', '47000.00'
#'Chava      Olsen    ', '47000.00'
#'Driscoll   Justice  ', '47000.00'
#'Patrick    Wolf     ', '47000.00'
#'Kelly      Mckinney ', '9000.00'
#'Emerson    Gonzalez ', '8800.00'
#'Sylvester  Horne    ', '6500.00'
#'Clarke     Jacobson ', '6400.00'


#9-PRODUCT MOST VALUE PER CATEGORY (FLIGHT, CRUISE, HOTEL, TRAIN)

SELECT ID_FLIGHT AS IDENTIFIER, PLANE AS PRODUCT,  ((F.TOTAL_SEAT_VIP*F.PRICE_VIP) + (F.TOTAL_SEAT_ECO*F.PRICE_ECO)) AS TOTAL_PRICE 
  FROM FLIGHT AS F WHERE ((F.TOTAL_SEAT_VIP*F.PRICE_VIP) + (F.TOTAL_SEAT_ECO*F.PRICE_ECO)) =(SELECT MAX(TEMP.TOTAL_FINAL) 
                                                                                               FROM (SELECT ((TOTAL_SEAT_VIP*PRICE_VIP) + (TOTAL_SEAT_ECO*PRICE_ECO)) AS TOTAL_FINAL 
 							                                                                           FROM FLIGHT) AS TEMP)
 UNION
 SELECT ID_TRAIN AS IDENTIFIER, TRAIN AS PRODUCT,  ((T.TOTAL_SEAT_VIP*T.PRICE_VIP) + (T.TOTAL_SEAT_COMMON*T.PRICE_COMMON)) AS TOTAL_PRICE 
  FROM TRAIN AS T WHERE ((T.TOTAL_SEAT_VIP*T.PRICE_VIP) + (T.TOTAL_SEAT_COMMON*T.PRICE_COMMON)) =(SELECT MAX(TEMP.TOTAL_FINAL) 
                                                                                                    FROM (SELECT ((TOTAL_SEAT_VIP*PRICE_VIP) + (TOTAL_SEAT_COMMON*PRICE_COMMON)) AS TOTAL_FINAL 
 							                                                                                FROM TRAIN) AS TEMP)
UNION
SELECT ID_CRUISE AS IDENTIFIER, SHIP AS PRODUCT,  ((C.TOTAL_ROOM_EXT*C.PRICE_EXT) + (C.TOTAL_ROOM_INT*C.PRICE_INT)) AS TOTAL_PRICE 
  FROM CRUISE AS C WHERE ((C.TOTAL_ROOM_EXT*C.PRICE_EXT) + (C.TOTAL_ROOM_INT*C.PRICE_INT)) =(SELECT MAX(TEMP.TOTAL_FINAL) 
                                                                                               FROM (SELECT ((TOTAL_ROOM_EXT*PRICE_EXT) + (TOTAL_ROOM_INT*PRICE_INT)) AS TOTAL_FINAL 
 							                                                                           FROM CRUISE) AS TEMP)
UNION  
SELECT ID_HOTEL AS IDENTIFIER, HOTEL AS PRODUCT,  ((H.TOTAL_SUITE*H.PRICE_SUITE) + (H.TOTAL_COMMON*H.PRICE_COMMON)) AS TOTAL_PRICE 
  FROM HOTEL AS H WHERE ((H.TOTAL_SUITE*H.PRICE_SUITE) + (H.TOTAL_COMMON*H.PRICE_COMMON)) =(SELECT MAX(TEMP.TOTAL_FINAL) 
                                                                                              FROM (SELECT ((TOTAL_SUITE*PRICE_SUITE) + (TOTAL_COMMON*PRICE_COMMON)) AS TOTAL_FINAL 
 							                                                                           FROM HOTEL) AS TEMP);
#Solution
#'YM8519', 'AIRBUS A380', '4292400.00'
#'YM8520', 'AIRBUS A380', '4292400.00'
#'YM8521', 'AIRBUS A380', '4292400.00'
#'YM8522', 'AIRBUS A380', '4292400.00'
#'YM8527', 'AIRBUS A380', '4292400.00'
#'YM8528', 'AIRBUS A380', '4292400.00'
#'AZ1011', 'AIRBUS A380', '4292400.00'
#'AZ1012', 'AIRBUS A380', '4292400.00'
#'AZ1013', 'AIRBUS A380', '4292400.00'
#'INT521', 'INT ZONA-B ', '3072200.00'
#'INT522', 'INT ZONA-B ', '3072200.00'
#'CR2005', 'MSC CRUCEROS      ', '8620000.00'
#'HT1001', 'HOTEL GRAN NACIONAL     ', '2650000.00'
#'HT1002', 'HOTEL PLAYA             ', '2650000.00'
#'HT1004', 'HOTEL INTERNACIONAL     ', '2650000.00'
#'HT1006', 'HOTEL INTERCONTINENTAL  ', '2650000.00'
#'HT1007', 'HOTEL URBAN             ', '2650000.00'
#'HT1008', 'HOTEL EL RESPLANDOR     ', '2650000.00'
#'HT1009', 'HOTEL LOS ALAMOS        ', '2650000.00'
#'HT1020', 'HOTEL MARBESOL          ', '2650000.00'
#'HT1021', 'HOTEL DON QUIXOTE       ', '2650000.00'
#'HT1022', 'HOTEL DULCINEA          ', '2650000.00'
#'HT1033', 'HOTEL GRAND INTERCONT   ', '2650000.00'
#'HT1034', 'HOTEL INTERNATIONAL     ', '2650000.00'
#'HT1035', 'HOTEL NATIONAL          ', '2650000.00'
#'HT1040', 'HOTEL RITZ              ', '2650000.00'




#10. CUSTOMER MOST LOYAL (MORE BOOKINGS MADE)

SELECT ID_CUST, CUST_NAME, SURNAME, COUNT(BOOK_NUMBER) AS TOTAL_BOOKINGS
  FROM BOOKS B JOIN CUSTOMER C ON (B.ID_CUST = C.IDENTIFIER)
 GROUP BY ID_CUST
HAVING COUNT(BOOK_NUMBER) =  (SELECT MAX(TEMP.COUNT_BOOK) 
                                FROM (SELECT COUNT(BOOK_NUMBER) AS COUNT_BOOK 
                                        FROM BOOKS GROUP BY ID_CUST) AS TEMP);

#Solution  
#168711173M	Sylvester 	Horne    	8