-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 13:27:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET FOREIGN_KEY_CHECKS = 0;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_ruben
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_ruben
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_ruben` DEFAULT CHARACTER SET utf8 ;
USE `database_ruben` ;

-- -----------------------------------------------------
-- Table `database_ruben`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`PROVINCIA` (
  `CODIGO` INT(2) NOT NULL,
  `NOMBRE` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`MUNICIPIO` (
  `CMUN` INT(5) NOT NULL,
  `CPROVIN` INT(2) NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `HOMBRES` INT(11) NULL,
  `MUJERES` INT(11) NULL,
  PRIMARY KEY (`CMUN`),
  INDEX `FK_PROVIN_COD_idx` (`CPROVIN` ASC) VISIBLE,
  CONSTRAINT `FK_PROVIN_COD`
    FOREIGN KEY (`CPROVIN`)
    REFERENCES `database_ruben`.`PROVINCIA` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`ALUMNOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`ALUMNOS` (
  `DNI` INT(9) NOT NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDO1` VARCHAR(20) NULL,
  `APELLIDO2` VARCHAR(20) NULL,
  `GENERO` VARCHAR(4) NULL,
  `DIRECCION` VARCHAR(100) NULL,
  `TELEFONO` VARCHAR(9) NULL,
  `EMAIL` VARCHAR(40) NULL,
  `FECHA_NACIMIENTO` DATE NULL,
  `FECHA_PRIM_MATRICULA` DATE NOT NULL,
  `CODMUNI` INT(5) NULL,
  `CODPROVIN` INT(5) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `FK_MUN_CODS_idx` (`CODMUNI` ASC, `CODPROVIN` ASC) VISIBLE,
  CONSTRAINT `FK_MUN_CODS`
    FOREIGN KEY (`CODMUNI` , `CODPROVIN`)
    REFERENCES `database_ruben`.`MUNICIPIO` (`CMUN` , `CPROVIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`DEPARTAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`DEPARTAMENTOS` (
  `CODIGO` INT(3) NOT NULL,
  `NOMBRE` VARCHAR(40) NOT NULL,
  `DIRECCION` VARCHAR(30) NULL,
  `TELEFONO` VARCHAR(9) NULL,
  `WEB` VARCHAR(30) NULL,
  `FECHA_CREACION` DATE NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`PROFESORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`PROFESORES` (
  `ID` VARCHAR(20) NOT NULL,
  `NOMBRE` VARCHAR(20) NOT NULL,
  `APELLIDO1` VARCHAR(20) NOT NULL,
  `APELLIDO2` VARCHAR(20) NULL,
  `TELEFONO` VARCHAR(4) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `DESPACHO` VARCHAR(10) NULL,
  `FECHA_NACIMIENTO` DATE NULL,
  `ANTIGÜEDAD` DATE NULL,
  `DEPART` INT(3) NULL,
  `TESIS` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_DEPT_COD_idx` (`DEPART` ASC) VISIBLE,
  INDEX `FK_PROF_ID_idx` (`TESIS` ASC) VISIBLE,
  CONSTRAINT `FK_DEPT_COD`
    FOREIGN KEY (`DEPART`)
    REFERENCES `database_ruben`.`DEPARTAMENTOS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROF_ID`
    FOREIGN KEY (`TESIS`)
    REFERENCES `database_ruben`.`PROFESORES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`MATERIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`MATERIAS` (
  `CODIGO` INT(2) NOT NULL,
  `NOMBRE` VARCHAR(40) NOT NULL,
  `DESCRIPCION` VARCHAR(200) NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`ASIGNATURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`ASIGNATURAS` (
  `CODIGO` INT(3) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `CREDITOS` DECIMAL(3,1) NULL,
  `TEORICOS` DECIMAL(3,1) NULL,
  `PRACTICOS` DECIMAL(3,1) NULL,
  `CARACTER` VARCHAR(2) NULL,
  `CURSO` INT(1) NULL,
  `WEB` VARCHAR(30) NULL,
  `CODMAT` INT(2) NULL,
  `CODDEPART` INT(3) NULL,
  PRIMARY KEY (`CODIGO`),
  INDEX `FK_MATERIAS_COD_idx` (`CODMAT` ASC) VISIBLE,
  INDEX `FK_DEPART_COD_idx` (`CODDEPART` ASC) VISIBLE,
  CONSTRAINT `FK_MATERIAS_COD`
    FOREIGN KEY (`CODMAT`)
    REFERENCES `database_ruben`.`MATERIAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DEPART_COD`
    FOREIGN KEY (`CODDEPART`)
    REFERENCES `database_ruben`.`DEPARTAMENTOS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`INVESTIGADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`INVESTIGADORES` (
  `ID_PROFESOR` VARCHAR(20) NOT NULL,
  `TRAMOS` INT(2) NULL,
  PRIMARY KEY (`ID_PROFESOR`),
  CONSTRAINT `FK_PROF_COD`
    FOREIGN KEY (`ID_PROFESOR`)
    REFERENCES `database_ruben`.`PROFESORES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`MATRICULAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`MATRICULAR` (
  `ASIGNATURA` INT(3) NOT NULL,
  `ALUMNO` INT(9) NOT NULL,
  `CURSO` VARCHAR(5) NOT NULL,
  `GRUPO` VARCHAR(1) NOT NULL,
  `CALIFICACION` INT NULL,
  PRIMARY KEY (`ASIGNATURA`, `ALUMNO`, `CURSO`, `GRUPO`),
  INDEX `FK_ALU_COD_idx` (`ALUMNO` ASC) VISIBLE,
  CONSTRAINT `FK_ASIG_COD`
    FOREIGN KEY (`ASIGNATURA`)
    REFERENCES `database_ruben`.`ASIGNATURAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ALU_COD`
    FOREIGN KEY (`ALUMNO`)
    REFERENCES `database_ruben`.`ALUMNOS` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`IMPARTIR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`IMPARTIR` (
  `C_ASIG` INT(3) NOT NULL,
  `C_PROF` VARCHAR(20) NOT NULL,
  `CURSO` VARCHAR(5) NOT NULL,
  `GRUPO` VARCHAR(1) NOT NULL,
  `CARGA_CREDITOS` DECIMAL(3,1) NULL,
  PRIMARY KEY (`C_ASIG`, `C_PROF`, `CURSO`, `GRUPO`),
  INDEX `FK_PROF_ID_idx` (`C_PROF` ASC) VISIBLE,
  CONSTRAINT `FK_ASIG_COD_IMP`
    FOREIGN KEY (`C_ASIG`)
    REFERENCES `database_ruben`.`ASIGNATURAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROF_ID_IMP`
    FOREIGN KEY (`C_PROF`)
    REFERENCES `database_ruben`.`PROFESORES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`CORREQUISITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`CORREQUISITO` (
  `COCORRE1` INT(3) NOT NULL,
  `COCORRE2` INT(3) NOT NULL,
  PRIMARY KEY (`COCORRE1`, `COCORRE2`),
  INDEX `FK_ASIG_COD2_idx` (`COCORRE2` ASC) VISIBLE,
  CONSTRAINT `FK_ASIG_COD1`
    FOREIGN KEY (`COCORRE1`)
    REFERENCES `database_ruben`.`ASIGNATURAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ASIG_COD2`
    FOREIGN KEY (`COCORRE2`)
    REFERENCES `database_ruben`.`ASIGNATURAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_ruben`.`PREREQUISITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_ruben`.`PREREQUISITO` (
  `COD_PRE` INT(3) NOT NULL,
  `COD_ASIG` INT(3) NOT NULL,
  PRIMARY KEY (`COD_PRE`, `COD_ASIG`),
  INDEX `FK_ASIG_COD_PRE2_idx` (`COD_ASIG` ASC) VISIBLE,
  CONSTRAINT `FK_ASIG_COD_PRE`
    FOREIGN KEY (`COD_PRE`)
    REFERENCES `database_ruben`.`ASIGNATURAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ASIG_COD_PRE2`
    FOREIGN KEY (`COD_ASIG`)
    REFERENCES `database_ruben`.`ASIGNATURAS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
