#EJERCICIO 1

SELECT P.ID, P.NOMBRE, P.APELLIDO1, P.APELLIDO2, A.CODIGO, A.NOMBRE
  FROM PROFESORES P, IMPARTIR I, ASIGNATURAS A
 WHERE (I.PROFESOR=P.ID)
   AND (I.ASIGNATURA=A.CODIGO);


#EJERCICIO 2

SELECT CONCAT(P1.NOMBRE, ' ', P1.APELLIDO1, ' ', IFNULL(P1.APELLIDO2, ' ')) 'PROFESORES',
       IFNULL(CONCAT(P2.NOMBRE, ' ', P2.APELLIDO1, ' ', IFNULL(P2.APELLIDO2, ' ')), 'NO TIENE') 'DIRECTOR TESIS'
  FROM PROFESORES P1 LEFT OUTER JOIN PROFESORES P2 ON P2.ID = P1.DIRECTOR_TESIS
 ORDER BY 2 DESC;



#EJERCICIO 3

SELECT P1.NOMBRE, P1.APELLIDO1, IFNULL(P1.APELLIDO2,' '), ABS(TIMESTAMPDIFF(YEAR, NOW(), P1.ANTIGÜEDAD)) 'ANTIGÜEDAD_1',
       P2.NOMBRE, P2.APELLIDO1, IFNULL(P1.APELLIDO2,' '), ABS(TIMESTAMPDIFF(YEAR, NOW(), P2.ANTIGÜEDAD)) 'ANTIGÜEDAD_2'
FROM PROFESORES P1, PROFESORES P2
WHERE P1.DEPARTAMENTO = P2.DEPARTAMENTO
AND ABS(TIMESTAMPDIFF(YEAR, P1.ANTIGÜEDAD,  P2.ANTIGÜEDAD)) < 2
AND P1.ID < P2.ID;


#EJERCICIO 4

SELECT ASIG1.NOMBRE "ASIGNATURA 1" , ASIG2.NOMBRE "ASIGNATURA 2" , ASIG3.NOMBRE "ASIGNATURA 3", ASIG1.COD_MATERIA
  FROM ASIGNATURAS ASIG1, ASIGNATURAS ASIG2, ASIGNATURAS ASIG3, MATERIAS M
 WHERE ASIG1.COD_MATERIA = M.CODIGO
   AND ASIG2.COD_MATERIA = M.CODIGO
   AND ASIG3.COD_MATERIA = M.CODIGO
   AND ASIG1.CODIGO < ASIG2.CODIGO
   AND ASIG2.CODIGO < ASIG3.CODIGO;


#EJERCICIO 5

SELECT ALUMNOS.NOMBRE,  ALUMNOS.APELLIDO1, ALUMNOS.APELLIDO2
  FROM (IMPARTIR NATURAL JOIN MATRICULAR) JOIN PROFESORES ON (IMPARTIR.PROFESOR = PROFESORES.ID)
  JOIN ALUMNOS ON MATRICULAR.ALUMNO = ALUMNOS.DNI
 WHERE UPPER(PROFESORES.NOMBRE) = 'ENRIQUE' AND PROFESORES.APELLIDO1 = 'SOLER'
 ORDER BY ALUMNOS.APELLIDO1, ALUMNOS.NOMBRE;


#EJERCICIO 6

SELECT  ASIG.NOMBRE "ASIGNATURA" , M.NOMBRE "MATERIA" ,
        CONCAT(P.NOMBRE, ' ', P.APELLIDO1, ' ', IFNULL(P.APELLIDO2, ' ')) AS "PROFESOR" , I.CARGA_CREDITOS
  FROM ASIGNATURAS ASIG JOIN IMPARTIR I ON (ASIG.CODIGO=I.ASIGNATURA) AND (I.CARGA_CREDITOS IS NOT NULL)
						JOIN PROFESORES P ON (P.ID=I.PROFESOR)
                        JOIN MATERIAS M ON (M.CODIGO=ASIG.COD_MATERIA)
 ORDER BY M.CODIGO , ASIG.NOMBRE DESC;


#EJERCICIO 7

SELECT ASIGNATURAS.NOMBRE 'ASIGNATURAS', DEPARTAMENTOS.NOMBRE 'DEPARTAMENTO', ASIGNATURAS.CREDITOS,
       TRUNCATE(ASIGNATURAS.PRACTICOS / ASIGNATURAS.CREDITOS * 100,2) '% CREDITOS PRACTICOS'
  FROM ASIGNATURAS, DEPARTAMENTOS
 WHERE ASIGNATURAS.DEPARTAMENTO = DEPARTAMENTOS.CODIGO
   AND CREDITOS IS NOT NULL AND ASIGNATURAS.PRACTICOS / ASIGNATURAS.CREDITOS * 100 IS NOT NULL
 ORDER BY 4 DESC;


#EJERCICIO 8

SELECT DISTINCT AL1.APELLIDO1 'APELLIDO CON LL'
  FROM ALUMNOS AL1
 WHERE AL1.APELLIDO1 LIKE '%LL%'
UNION
SELECT DISTINCT AL1.APELLIDO2
  FROM ALUMNOS AL1
 WHERE AL1.APELLIDO2 LIKE '%LL%'
UNION
SELECT DISTINCT P.APELLIDO1
  FROM PROFESORES P
 WHERE P.APELLIDO1 LIKE '%LL%'
UNION
SELECT DISTINCT P.APELLIDO2
  FROM PROFESORES P
 WHERE P.APELLIDO2 LIKE '%LL%';


#EJERCICIO 9

SELECT CONCAT('EL DIRECTOR DE:  ', P1.NOMBRE, ' ', P1.APELLIDO1, ' ', P2.APELLIDO2,' ES: ', P2.NOMBRE, ' ', P2.APELLIDO1, ' ', P2.APELLIDO2) 'PROFESOR DIREC',
       IFNULL(INVESTIGADORES.TRAMOS, 'NO TIENE') 'TRAMO DE INVESTIGACION'
  FROM PROFESORES P1 LEFT  JOIN PROFESORES P2 ON P2.ID = P1.DIRECTOR_TESIS LEFT JOIN INVESTIGADORES ON INVESTIGADORES.ID_PROFESOR = P2.ID
 WHERE P1.DIRECTOR_TESIS IS NOT NULL
 ORDER BY P1.APELLIDO1;


#EJERCICIO 10

SELECT CONCAT(A1.NOMBRE, ' ', A1.APELLIDO1, ' ', IFNULL(A1.APELLIDO2, ' ')) "ALUMNO1",
	   CONCAT(A2.NOMBRE, ' ', A2.APELLIDO1, ' ', IFNULL(A2.APELLIDO2, ' ')) "ALUMNO2"
 FROM ALUMNOS A1 LEFT OUTER JOIN ALUMNOS A2 ON (A1.DNI < A2.DNI) AND (A1.FECHA_PRIM_MATRICULA=A2.FECHA_PRIM_MATRICULA);
